### ISSUE TITLE
Display in ImageView

### ISSUE THREAD

**Issue by TavishBarua** [Whhoesj/lastfmfetcher#1]
How can i display the fetched AlbumArt into imageview?

**Comment by Whhoesj** [comment]
The easiest way is probably by using the library [Picasso](http://square.github.io/picasso).

After including that library in your project, it should be something like:
```java
Album someAlbum = lastFM.getAlbum("Florence + The Machine", "Ceremonials");
Picasso.with(context)
       .load(someAlbum.getImage().getLarge())
       .into(imageView);
```
